// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FollowCheckService.proto

package com.icemelon404.community.social.proto;

public interface FollowInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FollowInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 follower = 1;</code>
   * @return The follower.
   */
  long getFollower();

  /**
   * <code>int64 followee = 2;</code>
   * @return The followee.
   */
  long getFollowee();
}
