// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FollowCountService.proto

package com.icemelon404.community.social.proto;

/**
 * Protobuf type {@code FollowCount}
 */
public final class FollowCount extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:FollowCount)
    FollowCountOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FollowCount.newBuilder() to construct.
  private FollowCount(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FollowCount() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FollowCount();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FollowCount(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            followCount_ = input.readInt32();
            break;
          }
          case 16: {

            followerCount_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.icemelon404.community.social.proto.FollowCountServiceOuterClass.internal_static_FollowCount_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.icemelon404.community.social.proto.FollowCountServiceOuterClass.internal_static_FollowCount_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.icemelon404.community.social.proto.FollowCount.class, com.icemelon404.community.social.proto.FollowCount.Builder.class);
  }

  public static final int FOLLOWCOUNT_FIELD_NUMBER = 1;
  private int followCount_;
  /**
   * <code>int32 followCount = 1;</code>
   * @return The followCount.
   */
  @java.lang.Override
  public int getFollowCount() {
    return followCount_;
  }

  public static final int FOLLOWERCOUNT_FIELD_NUMBER = 2;
  private int followerCount_;
  /**
   * <code>int32 followerCount = 2;</code>
   * @return The followerCount.
   */
  @java.lang.Override
  public int getFollowerCount() {
    return followerCount_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (followCount_ != 0) {
      output.writeInt32(1, followCount_);
    }
    if (followerCount_ != 0) {
      output.writeInt32(2, followerCount_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (followCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, followCount_);
    }
    if (followerCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, followerCount_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.icemelon404.community.social.proto.FollowCount)) {
      return super.equals(obj);
    }
    com.icemelon404.community.social.proto.FollowCount other = (com.icemelon404.community.social.proto.FollowCount) obj;

    if (getFollowCount()
        != other.getFollowCount()) return false;
    if (getFollowerCount()
        != other.getFollowerCount()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FOLLOWCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getFollowCount();
    hash = (37 * hash) + FOLLOWERCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getFollowerCount();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.icemelon404.community.social.proto.FollowCount parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.icemelon404.community.social.proto.FollowCount parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.icemelon404.community.social.proto.FollowCount parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.icemelon404.community.social.proto.FollowCount parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.icemelon404.community.social.proto.FollowCount parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.icemelon404.community.social.proto.FollowCount parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.icemelon404.community.social.proto.FollowCount parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.icemelon404.community.social.proto.FollowCount parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.icemelon404.community.social.proto.FollowCount parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.icemelon404.community.social.proto.FollowCount parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.icemelon404.community.social.proto.FollowCount parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.icemelon404.community.social.proto.FollowCount parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.icemelon404.community.social.proto.FollowCount prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code FollowCount}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:FollowCount)
      com.icemelon404.community.social.proto.FollowCountOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.icemelon404.community.social.proto.FollowCountServiceOuterClass.internal_static_FollowCount_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.icemelon404.community.social.proto.FollowCountServiceOuterClass.internal_static_FollowCount_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.icemelon404.community.social.proto.FollowCount.class, com.icemelon404.community.social.proto.FollowCount.Builder.class);
    }

    // Construct using com.icemelon404.community.social.proto.FollowCount.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      followCount_ = 0;

      followerCount_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.icemelon404.community.social.proto.FollowCountServiceOuterClass.internal_static_FollowCount_descriptor;
    }

    @java.lang.Override
    public com.icemelon404.community.social.proto.FollowCount getDefaultInstanceForType() {
      return com.icemelon404.community.social.proto.FollowCount.getDefaultInstance();
    }

    @java.lang.Override
    public com.icemelon404.community.social.proto.FollowCount build() {
      com.icemelon404.community.social.proto.FollowCount result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.icemelon404.community.social.proto.FollowCount buildPartial() {
      com.icemelon404.community.social.proto.FollowCount result = new com.icemelon404.community.social.proto.FollowCount(this);
      result.followCount_ = followCount_;
      result.followerCount_ = followerCount_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.icemelon404.community.social.proto.FollowCount) {
        return mergeFrom((com.icemelon404.community.social.proto.FollowCount)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.icemelon404.community.social.proto.FollowCount other) {
      if (other == com.icemelon404.community.social.proto.FollowCount.getDefaultInstance()) return this;
      if (other.getFollowCount() != 0) {
        setFollowCount(other.getFollowCount());
      }
      if (other.getFollowerCount() != 0) {
        setFollowerCount(other.getFollowerCount());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.icemelon404.community.social.proto.FollowCount parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.icemelon404.community.social.proto.FollowCount) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int followCount_ ;
    /**
     * <code>int32 followCount = 1;</code>
     * @return The followCount.
     */
    @java.lang.Override
    public int getFollowCount() {
      return followCount_;
    }
    /**
     * <code>int32 followCount = 1;</code>
     * @param value The followCount to set.
     * @return This builder for chaining.
     */
    public Builder setFollowCount(int value) {
      
      followCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 followCount = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFollowCount() {
      
      followCount_ = 0;
      onChanged();
      return this;
    }

    private int followerCount_ ;
    /**
     * <code>int32 followerCount = 2;</code>
     * @return The followerCount.
     */
    @java.lang.Override
    public int getFollowerCount() {
      return followerCount_;
    }
    /**
     * <code>int32 followerCount = 2;</code>
     * @param value The followerCount to set.
     * @return This builder for chaining.
     */
    public Builder setFollowerCount(int value) {
      
      followerCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 followerCount = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFollowerCount() {
      
      followerCount_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:FollowCount)
  }

  // @@protoc_insertion_point(class_scope:FollowCount)
  private static final com.icemelon404.community.social.proto.FollowCount DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.icemelon404.community.social.proto.FollowCount();
  }

  public static com.icemelon404.community.social.proto.FollowCount getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FollowCount>
      PARSER = new com.google.protobuf.AbstractParser<FollowCount>() {
    @java.lang.Override
    public FollowCount parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FollowCount(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FollowCount> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FollowCount> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.icemelon404.community.social.proto.FollowCount getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

