// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FollowerFetchService.proto

package com.icemelon404.community.social.proto;

public final class FollowerFetchServiceOuterClass {
  private FollowerFetchServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Follower_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Follower_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FollowerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FollowerRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032FollowerFetchService.proto\"\026\n\010Follower" +
      "\022\n\n\002id\030\001 \001(\003\"H\n\017FollowerRequest\022\020\n\010follo" +
      "wee\030\001 \001(\003\022\020\n\010pageSize\030\002 \001(\005\022\021\n\tpageIndex" +
      "\030\003 \001(\0052G\n\024FollowerFetchService\022/\n\016fetchF" +
      "ollowers\022\020.FollowerRequest\032\t.Follower0\001B" +
      "*\n&com.icemelon404.community.social.prot" +
      "oP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Follower_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Follower_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Follower_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_FollowerRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_FollowerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FollowerRequest_descriptor,
        new java.lang.String[] { "Followee", "PageSize", "PageIndex", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
