// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FollowCheckService.proto

package com.icemelon404.community.social.proto;

/**
 * Protobuf type {@code FollowStatus}
 */
public final class FollowStatus extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:FollowStatus)
    FollowStatusOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FollowStatus.newBuilder() to construct.
  private FollowStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FollowStatus() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FollowStatus();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FollowStatus(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            isFollowing_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.icemelon404.community.social.proto.FollowCheckServiceOuterClass.internal_static_FollowStatus_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.icemelon404.community.social.proto.FollowCheckServiceOuterClass.internal_static_FollowStatus_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.icemelon404.community.social.proto.FollowStatus.class, com.icemelon404.community.social.proto.FollowStatus.Builder.class);
  }

  public static final int ISFOLLOWING_FIELD_NUMBER = 1;
  private boolean isFollowing_;
  /**
   * <code>bool isFollowing = 1;</code>
   * @return The isFollowing.
   */
  @java.lang.Override
  public boolean getIsFollowing() {
    return isFollowing_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (isFollowing_ != false) {
      output.writeBool(1, isFollowing_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (isFollowing_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, isFollowing_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.icemelon404.community.social.proto.FollowStatus)) {
      return super.equals(obj);
    }
    com.icemelon404.community.social.proto.FollowStatus other = (com.icemelon404.community.social.proto.FollowStatus) obj;

    if (getIsFollowing()
        != other.getIsFollowing()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ISFOLLOWING_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsFollowing());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.icemelon404.community.social.proto.FollowStatus parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.icemelon404.community.social.proto.FollowStatus parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.icemelon404.community.social.proto.FollowStatus parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.icemelon404.community.social.proto.FollowStatus parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.icemelon404.community.social.proto.FollowStatus parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.icemelon404.community.social.proto.FollowStatus parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.icemelon404.community.social.proto.FollowStatus parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.icemelon404.community.social.proto.FollowStatus parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.icemelon404.community.social.proto.FollowStatus parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.icemelon404.community.social.proto.FollowStatus parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.icemelon404.community.social.proto.FollowStatus parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.icemelon404.community.social.proto.FollowStatus parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.icemelon404.community.social.proto.FollowStatus prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code FollowStatus}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:FollowStatus)
      com.icemelon404.community.social.proto.FollowStatusOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.icemelon404.community.social.proto.FollowCheckServiceOuterClass.internal_static_FollowStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.icemelon404.community.social.proto.FollowCheckServiceOuterClass.internal_static_FollowStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.icemelon404.community.social.proto.FollowStatus.class, com.icemelon404.community.social.proto.FollowStatus.Builder.class);
    }

    // Construct using com.icemelon404.community.social.proto.FollowStatus.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      isFollowing_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.icemelon404.community.social.proto.FollowCheckServiceOuterClass.internal_static_FollowStatus_descriptor;
    }

    @java.lang.Override
    public com.icemelon404.community.social.proto.FollowStatus getDefaultInstanceForType() {
      return com.icemelon404.community.social.proto.FollowStatus.getDefaultInstance();
    }

    @java.lang.Override
    public com.icemelon404.community.social.proto.FollowStatus build() {
      com.icemelon404.community.social.proto.FollowStatus result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.icemelon404.community.social.proto.FollowStatus buildPartial() {
      com.icemelon404.community.social.proto.FollowStatus result = new com.icemelon404.community.social.proto.FollowStatus(this);
      result.isFollowing_ = isFollowing_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.icemelon404.community.social.proto.FollowStatus) {
        return mergeFrom((com.icemelon404.community.social.proto.FollowStatus)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.icemelon404.community.social.proto.FollowStatus other) {
      if (other == com.icemelon404.community.social.proto.FollowStatus.getDefaultInstance()) return this;
      if (other.getIsFollowing() != false) {
        setIsFollowing(other.getIsFollowing());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.icemelon404.community.social.proto.FollowStatus parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.icemelon404.community.social.proto.FollowStatus) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private boolean isFollowing_ ;
    /**
     * <code>bool isFollowing = 1;</code>
     * @return The isFollowing.
     */
    @java.lang.Override
    public boolean getIsFollowing() {
      return isFollowing_;
    }
    /**
     * <code>bool isFollowing = 1;</code>
     * @param value The isFollowing to set.
     * @return This builder for chaining.
     */
    public Builder setIsFollowing(boolean value) {
      
      isFollowing_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool isFollowing = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsFollowing() {
      
      isFollowing_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:FollowStatus)
  }

  // @@protoc_insertion_point(class_scope:FollowStatus)
  private static final com.icemelon404.community.social.proto.FollowStatus DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.icemelon404.community.social.proto.FollowStatus();
  }

  public static com.icemelon404.community.social.proto.FollowStatus getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FollowStatus>
      PARSER = new com.google.protobuf.AbstractParser<FollowStatus>() {
    @java.lang.Override
    public FollowStatus parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FollowStatus(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FollowStatus> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FollowStatus> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.icemelon404.community.social.proto.FollowStatus getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

