// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FollowCheckService.proto

package com.icemelon404.community.social.proto;

public final class FollowCheckServiceOuterClass {
  private FollowCheckServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FollowStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FollowStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FollowInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FollowInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030FollowCheckService.proto\"#\n\014FollowStat" +
      "us\022\023\n\013isFollowing\030\001 \001(\010\"0\n\nFollowInfo\022\020\n" +
      "\010follower\030\001 \001(\003\022\020\n\010followee\030\002 \001(\0032?\n\022Fol" +
      "lowCheckService\022)\n\013checkFollow\022\013.FollowI" +
      "nfo\032\r.FollowStatusB*\n&com.icemelon404.co" +
      "mmunity.social.protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_FollowStatus_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FollowStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FollowStatus_descriptor,
        new java.lang.String[] { "IsFollowing", });
    internal_static_FollowInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_FollowInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FollowInfo_descriptor,
        new java.lang.String[] { "Follower", "Followee", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
