// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FollowerFetchService.proto

package com.icemelon404.community.social.proto;

public interface FollowerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Follower)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();
}
