// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FollowerFetchService.proto

package com.icemelon404.community.social.proto;

/**
 * Protobuf type {@code FollowerRequest}
 */
public final class FollowerRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:FollowerRequest)
    FollowerRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FollowerRequest.newBuilder() to construct.
  private FollowerRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FollowerRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FollowerRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FollowerRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            followee_ = input.readInt64();
            break;
          }
          case 16: {

            pageSize_ = input.readInt32();
            break;
          }
          case 24: {

            pageIndex_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.icemelon404.community.social.proto.FollowerFetchServiceOuterClass.internal_static_FollowerRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.icemelon404.community.social.proto.FollowerFetchServiceOuterClass.internal_static_FollowerRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.icemelon404.community.social.proto.FollowerRequest.class, com.icemelon404.community.social.proto.FollowerRequest.Builder.class);
  }

  public static final int FOLLOWEE_FIELD_NUMBER = 1;
  private long followee_;
  /**
   * <code>int64 followee = 1;</code>
   * @return The followee.
   */
  @java.lang.Override
  public long getFollowee() {
    return followee_;
  }

  public static final int PAGESIZE_FIELD_NUMBER = 2;
  private int pageSize_;
  /**
   * <code>int32 pageSize = 2;</code>
   * @return The pageSize.
   */
  @java.lang.Override
  public int getPageSize() {
    return pageSize_;
  }

  public static final int PAGEINDEX_FIELD_NUMBER = 3;
  private int pageIndex_;
  /**
   * <code>int32 pageIndex = 3;</code>
   * @return The pageIndex.
   */
  @java.lang.Override
  public int getPageIndex() {
    return pageIndex_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (followee_ != 0L) {
      output.writeInt64(1, followee_);
    }
    if (pageSize_ != 0) {
      output.writeInt32(2, pageSize_);
    }
    if (pageIndex_ != 0) {
      output.writeInt32(3, pageIndex_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (followee_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, followee_);
    }
    if (pageSize_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, pageSize_);
    }
    if (pageIndex_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, pageIndex_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.icemelon404.community.social.proto.FollowerRequest)) {
      return super.equals(obj);
    }
    com.icemelon404.community.social.proto.FollowerRequest other = (com.icemelon404.community.social.proto.FollowerRequest) obj;

    if (getFollowee()
        != other.getFollowee()) return false;
    if (getPageSize()
        != other.getPageSize()) return false;
    if (getPageIndex()
        != other.getPageIndex()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FOLLOWEE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getFollowee());
    hash = (37 * hash) + PAGESIZE_FIELD_NUMBER;
    hash = (53 * hash) + getPageSize();
    hash = (37 * hash) + PAGEINDEX_FIELD_NUMBER;
    hash = (53 * hash) + getPageIndex();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.icemelon404.community.social.proto.FollowerRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.icemelon404.community.social.proto.FollowerRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.icemelon404.community.social.proto.FollowerRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.icemelon404.community.social.proto.FollowerRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.icemelon404.community.social.proto.FollowerRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.icemelon404.community.social.proto.FollowerRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.icemelon404.community.social.proto.FollowerRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.icemelon404.community.social.proto.FollowerRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.icemelon404.community.social.proto.FollowerRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.icemelon404.community.social.proto.FollowerRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.icemelon404.community.social.proto.FollowerRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.icemelon404.community.social.proto.FollowerRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.icemelon404.community.social.proto.FollowerRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code FollowerRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:FollowerRequest)
      com.icemelon404.community.social.proto.FollowerRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.icemelon404.community.social.proto.FollowerFetchServiceOuterClass.internal_static_FollowerRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.icemelon404.community.social.proto.FollowerFetchServiceOuterClass.internal_static_FollowerRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.icemelon404.community.social.proto.FollowerRequest.class, com.icemelon404.community.social.proto.FollowerRequest.Builder.class);
    }

    // Construct using com.icemelon404.community.social.proto.FollowerRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      followee_ = 0L;

      pageSize_ = 0;

      pageIndex_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.icemelon404.community.social.proto.FollowerFetchServiceOuterClass.internal_static_FollowerRequest_descriptor;
    }

    @java.lang.Override
    public com.icemelon404.community.social.proto.FollowerRequest getDefaultInstanceForType() {
      return com.icemelon404.community.social.proto.FollowerRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.icemelon404.community.social.proto.FollowerRequest build() {
      com.icemelon404.community.social.proto.FollowerRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.icemelon404.community.social.proto.FollowerRequest buildPartial() {
      com.icemelon404.community.social.proto.FollowerRequest result = new com.icemelon404.community.social.proto.FollowerRequest(this);
      result.followee_ = followee_;
      result.pageSize_ = pageSize_;
      result.pageIndex_ = pageIndex_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.icemelon404.community.social.proto.FollowerRequest) {
        return mergeFrom((com.icemelon404.community.social.proto.FollowerRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.icemelon404.community.social.proto.FollowerRequest other) {
      if (other == com.icemelon404.community.social.proto.FollowerRequest.getDefaultInstance()) return this;
      if (other.getFollowee() != 0L) {
        setFollowee(other.getFollowee());
      }
      if (other.getPageSize() != 0) {
        setPageSize(other.getPageSize());
      }
      if (other.getPageIndex() != 0) {
        setPageIndex(other.getPageIndex());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.icemelon404.community.social.proto.FollowerRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.icemelon404.community.social.proto.FollowerRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long followee_ ;
    /**
     * <code>int64 followee = 1;</code>
     * @return The followee.
     */
    @java.lang.Override
    public long getFollowee() {
      return followee_;
    }
    /**
     * <code>int64 followee = 1;</code>
     * @param value The followee to set.
     * @return This builder for chaining.
     */
    public Builder setFollowee(long value) {
      
      followee_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 followee = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFollowee() {
      
      followee_ = 0L;
      onChanged();
      return this;
    }

    private int pageSize_ ;
    /**
     * <code>int32 pageSize = 2;</code>
     * @return The pageSize.
     */
    @java.lang.Override
    public int getPageSize() {
      return pageSize_;
    }
    /**
     * <code>int32 pageSize = 2;</code>
     * @param value The pageSize to set.
     * @return This builder for chaining.
     */
    public Builder setPageSize(int value) {
      
      pageSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 pageSize = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPageSize() {
      
      pageSize_ = 0;
      onChanged();
      return this;
    }

    private int pageIndex_ ;
    /**
     * <code>int32 pageIndex = 3;</code>
     * @return The pageIndex.
     */
    @java.lang.Override
    public int getPageIndex() {
      return pageIndex_;
    }
    /**
     * <code>int32 pageIndex = 3;</code>
     * @param value The pageIndex to set.
     * @return This builder for chaining.
     */
    public Builder setPageIndex(int value) {
      
      pageIndex_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 pageIndex = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPageIndex() {
      
      pageIndex_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:FollowerRequest)
  }

  // @@protoc_insertion_point(class_scope:FollowerRequest)
  private static final com.icemelon404.community.social.proto.FollowerRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.icemelon404.community.social.proto.FollowerRequest();
  }

  public static com.icemelon404.community.social.proto.FollowerRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FollowerRequest>
      PARSER = new com.google.protobuf.AbstractParser<FollowerRequest>() {
    @java.lang.Override
    public FollowerRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FollowerRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FollowerRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FollowerRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.icemelon404.community.social.proto.FollowerRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

