// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FollowerFetchService.proto

package com.icemelon404.community.social.proto;

public interface FollowerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FollowerRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 followee = 1;</code>
   * @return The followee.
   */
  long getFollowee();

  /**
   * <code>int32 pageSize = 2;</code>
   * @return The pageSize.
   */
  int getPageSize();

  /**
   * <code>int32 pageIndex = 3;</code>
   * @return The pageIndex.
   */
  int getPageIndex();
}
