// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FollowCheckService.proto

package com.icemelon404.community.social.proto;

public interface FollowStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FollowStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool isFollowing = 1;</code>
   * @return The isFollowing.
   */
  boolean getIsFollowing();
}
