// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FollowCountService.proto

package com.icemelon404.community.social.proto;

public interface FollowCountOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FollowCount)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 followCount = 1;</code>
   * @return The followCount.
   */
  int getFollowCount();

  /**
   * <code>int32 followerCount = 2;</code>
   * @return The followerCount.
   */
  int getFollowerCount();
}
