// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FollowCountService.proto

package com.icemelon404.community.social.proto;

public interface UserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:User)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 userId = 1;</code>
   * @return The userId.
   */
  long getUserId();
}
