// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FeedServiceProto.proto

package com.icemelon404.community.feed.proto;

/**
 * Protobuf type {@code FeedRequest}
 */
public final class FeedRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:FeedRequest)
    FeedRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FeedRequest.newBuilder() to construct.
  private FeedRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FeedRequest() {
    direction_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FeedRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FeedRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            feedOwnerId_ = input.readInt64();
            break;
          }
          case 16: {

            boundary_ = input.readInt64();
            break;
          }
          case 24: {

            size_ = input.readInt32();
            break;
          }
          case 32: {
            int rawValue = input.readEnum();

            direction_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.icemelon404.community.feed.proto.FeedServiceProto.internal_static_FeedRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.icemelon404.community.feed.proto.FeedServiceProto.internal_static_FeedRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.icemelon404.community.feed.proto.FeedRequest.class, com.icemelon404.community.feed.proto.FeedRequest.Builder.class);
  }

  public static final int FEEDOWNERID_FIELD_NUMBER = 1;
  private long feedOwnerId_;
  /**
   * <code>int64 feedOwnerId = 1;</code>
   * @return The feedOwnerId.
   */
  @java.lang.Override
  public long getFeedOwnerId() {
    return feedOwnerId_;
  }

  public static final int BOUNDARY_FIELD_NUMBER = 2;
  private long boundary_;
  /**
   * <code>int64 boundary = 2;</code>
   * @return The boundary.
   */
  @java.lang.Override
  public long getBoundary() {
    return boundary_;
  }

  public static final int SIZE_FIELD_NUMBER = 3;
  private int size_;
  /**
   * <code>int32 size = 3;</code>
   * @return The size.
   */
  @java.lang.Override
  public int getSize() {
    return size_;
  }

  public static final int DIRECTION_FIELD_NUMBER = 4;
  private int direction_;
  /**
   * <code>.Direction direction = 4;</code>
   * @return The enum numeric value on the wire for direction.
   */
  @java.lang.Override public int getDirectionValue() {
    return direction_;
  }
  /**
   * <code>.Direction direction = 4;</code>
   * @return The direction.
   */
  @java.lang.Override public com.icemelon404.community.feed.proto.Direction getDirection() {
    @SuppressWarnings("deprecation")
    com.icemelon404.community.feed.proto.Direction result = com.icemelon404.community.feed.proto.Direction.valueOf(direction_);
    return result == null ? com.icemelon404.community.feed.proto.Direction.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (feedOwnerId_ != 0L) {
      output.writeInt64(1, feedOwnerId_);
    }
    if (boundary_ != 0L) {
      output.writeInt64(2, boundary_);
    }
    if (size_ != 0) {
      output.writeInt32(3, size_);
    }
    if (direction_ != com.icemelon404.community.feed.proto.Direction.UPPER.getNumber()) {
      output.writeEnum(4, direction_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (feedOwnerId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, feedOwnerId_);
    }
    if (boundary_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, boundary_);
    }
    if (size_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, size_);
    }
    if (direction_ != com.icemelon404.community.feed.proto.Direction.UPPER.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, direction_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.icemelon404.community.feed.proto.FeedRequest)) {
      return super.equals(obj);
    }
    com.icemelon404.community.feed.proto.FeedRequest other = (com.icemelon404.community.feed.proto.FeedRequest) obj;

    if (getFeedOwnerId()
        != other.getFeedOwnerId()) return false;
    if (getBoundary()
        != other.getBoundary()) return false;
    if (getSize()
        != other.getSize()) return false;
    if (direction_ != other.direction_) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FEEDOWNERID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getFeedOwnerId());
    hash = (37 * hash) + BOUNDARY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBoundary());
    hash = (37 * hash) + SIZE_FIELD_NUMBER;
    hash = (53 * hash) + getSize();
    hash = (37 * hash) + DIRECTION_FIELD_NUMBER;
    hash = (53 * hash) + direction_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.icemelon404.community.feed.proto.FeedRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.icemelon404.community.feed.proto.FeedRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.icemelon404.community.feed.proto.FeedRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.icemelon404.community.feed.proto.FeedRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.icemelon404.community.feed.proto.FeedRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.icemelon404.community.feed.proto.FeedRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.icemelon404.community.feed.proto.FeedRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.icemelon404.community.feed.proto.FeedRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.icemelon404.community.feed.proto.FeedRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.icemelon404.community.feed.proto.FeedRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.icemelon404.community.feed.proto.FeedRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.icemelon404.community.feed.proto.FeedRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.icemelon404.community.feed.proto.FeedRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code FeedRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:FeedRequest)
      com.icemelon404.community.feed.proto.FeedRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.icemelon404.community.feed.proto.FeedServiceProto.internal_static_FeedRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.icemelon404.community.feed.proto.FeedServiceProto.internal_static_FeedRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.icemelon404.community.feed.proto.FeedRequest.class, com.icemelon404.community.feed.proto.FeedRequest.Builder.class);
    }

    // Construct using com.icemelon404.community.feed.proto.FeedRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      feedOwnerId_ = 0L;

      boundary_ = 0L;

      size_ = 0;

      direction_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.icemelon404.community.feed.proto.FeedServiceProto.internal_static_FeedRequest_descriptor;
    }

    @java.lang.Override
    public com.icemelon404.community.feed.proto.FeedRequest getDefaultInstanceForType() {
      return com.icemelon404.community.feed.proto.FeedRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.icemelon404.community.feed.proto.FeedRequest build() {
      com.icemelon404.community.feed.proto.FeedRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.icemelon404.community.feed.proto.FeedRequest buildPartial() {
      com.icemelon404.community.feed.proto.FeedRequest result = new com.icemelon404.community.feed.proto.FeedRequest(this);
      result.feedOwnerId_ = feedOwnerId_;
      result.boundary_ = boundary_;
      result.size_ = size_;
      result.direction_ = direction_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.icemelon404.community.feed.proto.FeedRequest) {
        return mergeFrom((com.icemelon404.community.feed.proto.FeedRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.icemelon404.community.feed.proto.FeedRequest other) {
      if (other == com.icemelon404.community.feed.proto.FeedRequest.getDefaultInstance()) return this;
      if (other.getFeedOwnerId() != 0L) {
        setFeedOwnerId(other.getFeedOwnerId());
      }
      if (other.getBoundary() != 0L) {
        setBoundary(other.getBoundary());
      }
      if (other.getSize() != 0) {
        setSize(other.getSize());
      }
      if (other.direction_ != 0) {
        setDirectionValue(other.getDirectionValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.icemelon404.community.feed.proto.FeedRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.icemelon404.community.feed.proto.FeedRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long feedOwnerId_ ;
    /**
     * <code>int64 feedOwnerId = 1;</code>
     * @return The feedOwnerId.
     */
    @java.lang.Override
    public long getFeedOwnerId() {
      return feedOwnerId_;
    }
    /**
     * <code>int64 feedOwnerId = 1;</code>
     * @param value The feedOwnerId to set.
     * @return This builder for chaining.
     */
    public Builder setFeedOwnerId(long value) {
      
      feedOwnerId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 feedOwnerId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFeedOwnerId() {
      
      feedOwnerId_ = 0L;
      onChanged();
      return this;
    }

    private long boundary_ ;
    /**
     * <code>int64 boundary = 2;</code>
     * @return The boundary.
     */
    @java.lang.Override
    public long getBoundary() {
      return boundary_;
    }
    /**
     * <code>int64 boundary = 2;</code>
     * @param value The boundary to set.
     * @return This builder for chaining.
     */
    public Builder setBoundary(long value) {
      
      boundary_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 boundary = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearBoundary() {
      
      boundary_ = 0L;
      onChanged();
      return this;
    }

    private int size_ ;
    /**
     * <code>int32 size = 3;</code>
     * @return The size.
     */
    @java.lang.Override
    public int getSize() {
      return size_;
    }
    /**
     * <code>int32 size = 3;</code>
     * @param value The size to set.
     * @return This builder for chaining.
     */
    public Builder setSize(int value) {
      
      size_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 size = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSize() {
      
      size_ = 0;
      onChanged();
      return this;
    }

    private int direction_ = 0;
    /**
     * <code>.Direction direction = 4;</code>
     * @return The enum numeric value on the wire for direction.
     */
    @java.lang.Override public int getDirectionValue() {
      return direction_;
    }
    /**
     * <code>.Direction direction = 4;</code>
     * @param value The enum numeric value on the wire for direction to set.
     * @return This builder for chaining.
     */
    public Builder setDirectionValue(int value) {
      
      direction_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.Direction direction = 4;</code>
     * @return The direction.
     */
    @java.lang.Override
    public com.icemelon404.community.feed.proto.Direction getDirection() {
      @SuppressWarnings("deprecation")
      com.icemelon404.community.feed.proto.Direction result = com.icemelon404.community.feed.proto.Direction.valueOf(direction_);
      return result == null ? com.icemelon404.community.feed.proto.Direction.UNRECOGNIZED : result;
    }
    /**
     * <code>.Direction direction = 4;</code>
     * @param value The direction to set.
     * @return This builder for chaining.
     */
    public Builder setDirection(com.icemelon404.community.feed.proto.Direction value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      direction_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.Direction direction = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDirection() {
      
      direction_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:FeedRequest)
  }

  // @@protoc_insertion_point(class_scope:FeedRequest)
  private static final com.icemelon404.community.feed.proto.FeedRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.icemelon404.community.feed.proto.FeedRequest();
  }

  public static com.icemelon404.community.feed.proto.FeedRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FeedRequest>
      PARSER = new com.google.protobuf.AbstractParser<FeedRequest>() {
    @java.lang.Override
    public FeedRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FeedRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FeedRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FeedRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.icemelon404.community.feed.proto.FeedRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

