// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FeedServiceProto.proto

package com.icemelon404.community.feed.proto;

public interface FeedResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FeedResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int64 postId = 1 [packed = true];</code>
   * @return A list containing the postId.
   */
  java.util.List<java.lang.Long> getPostIdList();
  /**
   * <code>repeated int64 postId = 1 [packed = true];</code>
   * @return The count of postId.
   */
  int getPostIdCount();
  /**
   * <code>repeated int64 postId = 1 [packed = true];</code>
   * @param index The index of the element to return.
   * @return The postId at the given index.
   */
  long getPostId(int index);
}
