// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FeedServiceProto.proto

package com.icemelon404.community.feed.proto;

public interface FeedRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FeedRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 feedOwnerId = 1;</code>
   * @return The feedOwnerId.
   */
  long getFeedOwnerId();

  /**
   * <code>int64 boundary = 2;</code>
   * @return The boundary.
   */
  long getBoundary();

  /**
   * <code>int32 size = 3;</code>
   * @return The size.
   */
  int getSize();

  /**
   * <code>.Direction direction = 4;</code>
   * @return The enum numeric value on the wire for direction.
   */
  int getDirectionValue();
  /**
   * <code>.Direction direction = 4;</code>
   * @return The direction.
   */
  com.icemelon404.community.feed.proto.Direction getDirection();
}
