// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FeedServiceProto.proto

package com.icemelon404.community.feed.proto;

public interface FeedPushRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FeedPushRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .UserWithPost userWithPost = 1;</code>
   */
  java.util.List<com.icemelon404.community.feed.proto.UserWithPost> 
      getUserWithPostList();
  /**
   * <code>repeated .UserWithPost userWithPost = 1;</code>
   */
  com.icemelon404.community.feed.proto.UserWithPost getUserWithPost(int index);
  /**
   * <code>repeated .UserWithPost userWithPost = 1;</code>
   */
  int getUserWithPostCount();
  /**
   * <code>repeated .UserWithPost userWithPost = 1;</code>
   */
  java.util.List<? extends com.icemelon404.community.feed.proto.UserWithPostOrBuilder> 
      getUserWithPostOrBuilderList();
  /**
   * <code>repeated .UserWithPost userWithPost = 1;</code>
   */
  com.icemelon404.community.feed.proto.UserWithPostOrBuilder getUserWithPostOrBuilder(
      int index);
}
