// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FeedServiceProto.proto

package com.icemelon404.community.feed.proto;

/**
 * Protobuf type {@code FeedPushRequest}
 */
public final class FeedPushRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:FeedPushRequest)
    FeedPushRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FeedPushRequest.newBuilder() to construct.
  private FeedPushRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FeedPushRequest() {
    userWithPost_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FeedPushRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FeedPushRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              userWithPost_ = new java.util.ArrayList<com.icemelon404.community.feed.proto.UserWithPost>();
              mutable_bitField0_ |= 0x00000001;
            }
            userWithPost_.add(
                input.readMessage(com.icemelon404.community.feed.proto.UserWithPost.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        userWithPost_ = java.util.Collections.unmodifiableList(userWithPost_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.icemelon404.community.feed.proto.FeedServiceProto.internal_static_FeedPushRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.icemelon404.community.feed.proto.FeedServiceProto.internal_static_FeedPushRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.icemelon404.community.feed.proto.FeedPushRequest.class, com.icemelon404.community.feed.proto.FeedPushRequest.Builder.class);
  }

  public static final int USERWITHPOST_FIELD_NUMBER = 1;
  private java.util.List<com.icemelon404.community.feed.proto.UserWithPost> userWithPost_;
  /**
   * <code>repeated .UserWithPost userWithPost = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.icemelon404.community.feed.proto.UserWithPost> getUserWithPostList() {
    return userWithPost_;
  }
  /**
   * <code>repeated .UserWithPost userWithPost = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.icemelon404.community.feed.proto.UserWithPostOrBuilder> 
      getUserWithPostOrBuilderList() {
    return userWithPost_;
  }
  /**
   * <code>repeated .UserWithPost userWithPost = 1;</code>
   */
  @java.lang.Override
  public int getUserWithPostCount() {
    return userWithPost_.size();
  }
  /**
   * <code>repeated .UserWithPost userWithPost = 1;</code>
   */
  @java.lang.Override
  public com.icemelon404.community.feed.proto.UserWithPost getUserWithPost(int index) {
    return userWithPost_.get(index);
  }
  /**
   * <code>repeated .UserWithPost userWithPost = 1;</code>
   */
  @java.lang.Override
  public com.icemelon404.community.feed.proto.UserWithPostOrBuilder getUserWithPostOrBuilder(
      int index) {
    return userWithPost_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < userWithPost_.size(); i++) {
      output.writeMessage(1, userWithPost_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < userWithPost_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, userWithPost_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.icemelon404.community.feed.proto.FeedPushRequest)) {
      return super.equals(obj);
    }
    com.icemelon404.community.feed.proto.FeedPushRequest other = (com.icemelon404.community.feed.proto.FeedPushRequest) obj;

    if (!getUserWithPostList()
        .equals(other.getUserWithPostList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getUserWithPostCount() > 0) {
      hash = (37 * hash) + USERWITHPOST_FIELD_NUMBER;
      hash = (53 * hash) + getUserWithPostList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.icemelon404.community.feed.proto.FeedPushRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.icemelon404.community.feed.proto.FeedPushRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.icemelon404.community.feed.proto.FeedPushRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.icemelon404.community.feed.proto.FeedPushRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.icemelon404.community.feed.proto.FeedPushRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.icemelon404.community.feed.proto.FeedPushRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.icemelon404.community.feed.proto.FeedPushRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.icemelon404.community.feed.proto.FeedPushRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.icemelon404.community.feed.proto.FeedPushRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.icemelon404.community.feed.proto.FeedPushRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.icemelon404.community.feed.proto.FeedPushRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.icemelon404.community.feed.proto.FeedPushRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.icemelon404.community.feed.proto.FeedPushRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code FeedPushRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:FeedPushRequest)
      com.icemelon404.community.feed.proto.FeedPushRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.icemelon404.community.feed.proto.FeedServiceProto.internal_static_FeedPushRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.icemelon404.community.feed.proto.FeedServiceProto.internal_static_FeedPushRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.icemelon404.community.feed.proto.FeedPushRequest.class, com.icemelon404.community.feed.proto.FeedPushRequest.Builder.class);
    }

    // Construct using com.icemelon404.community.feed.proto.FeedPushRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getUserWithPostFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (userWithPostBuilder_ == null) {
        userWithPost_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        userWithPostBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.icemelon404.community.feed.proto.FeedServiceProto.internal_static_FeedPushRequest_descriptor;
    }

    @java.lang.Override
    public com.icemelon404.community.feed.proto.FeedPushRequest getDefaultInstanceForType() {
      return com.icemelon404.community.feed.proto.FeedPushRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.icemelon404.community.feed.proto.FeedPushRequest build() {
      com.icemelon404.community.feed.proto.FeedPushRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.icemelon404.community.feed.proto.FeedPushRequest buildPartial() {
      com.icemelon404.community.feed.proto.FeedPushRequest result = new com.icemelon404.community.feed.proto.FeedPushRequest(this);
      int from_bitField0_ = bitField0_;
      if (userWithPostBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          userWithPost_ = java.util.Collections.unmodifiableList(userWithPost_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.userWithPost_ = userWithPost_;
      } else {
        result.userWithPost_ = userWithPostBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.icemelon404.community.feed.proto.FeedPushRequest) {
        return mergeFrom((com.icemelon404.community.feed.proto.FeedPushRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.icemelon404.community.feed.proto.FeedPushRequest other) {
      if (other == com.icemelon404.community.feed.proto.FeedPushRequest.getDefaultInstance()) return this;
      if (userWithPostBuilder_ == null) {
        if (!other.userWithPost_.isEmpty()) {
          if (userWithPost_.isEmpty()) {
            userWithPost_ = other.userWithPost_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureUserWithPostIsMutable();
            userWithPost_.addAll(other.userWithPost_);
          }
          onChanged();
        }
      } else {
        if (!other.userWithPost_.isEmpty()) {
          if (userWithPostBuilder_.isEmpty()) {
            userWithPostBuilder_.dispose();
            userWithPostBuilder_ = null;
            userWithPost_ = other.userWithPost_;
            bitField0_ = (bitField0_ & ~0x00000001);
            userWithPostBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getUserWithPostFieldBuilder() : null;
          } else {
            userWithPostBuilder_.addAllMessages(other.userWithPost_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.icemelon404.community.feed.proto.FeedPushRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.icemelon404.community.feed.proto.FeedPushRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.icemelon404.community.feed.proto.UserWithPost> userWithPost_ =
      java.util.Collections.emptyList();
    private void ensureUserWithPostIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        userWithPost_ = new java.util.ArrayList<com.icemelon404.community.feed.proto.UserWithPost>(userWithPost_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.icemelon404.community.feed.proto.UserWithPost, com.icemelon404.community.feed.proto.UserWithPost.Builder, com.icemelon404.community.feed.proto.UserWithPostOrBuilder> userWithPostBuilder_;

    /**
     * <code>repeated .UserWithPost userWithPost = 1;</code>
     */
    public java.util.List<com.icemelon404.community.feed.proto.UserWithPost> getUserWithPostList() {
      if (userWithPostBuilder_ == null) {
        return java.util.Collections.unmodifiableList(userWithPost_);
      } else {
        return userWithPostBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .UserWithPost userWithPost = 1;</code>
     */
    public int getUserWithPostCount() {
      if (userWithPostBuilder_ == null) {
        return userWithPost_.size();
      } else {
        return userWithPostBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .UserWithPost userWithPost = 1;</code>
     */
    public com.icemelon404.community.feed.proto.UserWithPost getUserWithPost(int index) {
      if (userWithPostBuilder_ == null) {
        return userWithPost_.get(index);
      } else {
        return userWithPostBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .UserWithPost userWithPost = 1;</code>
     */
    public Builder setUserWithPost(
        int index, com.icemelon404.community.feed.proto.UserWithPost value) {
      if (userWithPostBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUserWithPostIsMutable();
        userWithPost_.set(index, value);
        onChanged();
      } else {
        userWithPostBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .UserWithPost userWithPost = 1;</code>
     */
    public Builder setUserWithPost(
        int index, com.icemelon404.community.feed.proto.UserWithPost.Builder builderForValue) {
      if (userWithPostBuilder_ == null) {
        ensureUserWithPostIsMutable();
        userWithPost_.set(index, builderForValue.build());
        onChanged();
      } else {
        userWithPostBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .UserWithPost userWithPost = 1;</code>
     */
    public Builder addUserWithPost(com.icemelon404.community.feed.proto.UserWithPost value) {
      if (userWithPostBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUserWithPostIsMutable();
        userWithPost_.add(value);
        onChanged();
      } else {
        userWithPostBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .UserWithPost userWithPost = 1;</code>
     */
    public Builder addUserWithPost(
        int index, com.icemelon404.community.feed.proto.UserWithPost value) {
      if (userWithPostBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUserWithPostIsMutable();
        userWithPost_.add(index, value);
        onChanged();
      } else {
        userWithPostBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .UserWithPost userWithPost = 1;</code>
     */
    public Builder addUserWithPost(
        com.icemelon404.community.feed.proto.UserWithPost.Builder builderForValue) {
      if (userWithPostBuilder_ == null) {
        ensureUserWithPostIsMutable();
        userWithPost_.add(builderForValue.build());
        onChanged();
      } else {
        userWithPostBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .UserWithPost userWithPost = 1;</code>
     */
    public Builder addUserWithPost(
        int index, com.icemelon404.community.feed.proto.UserWithPost.Builder builderForValue) {
      if (userWithPostBuilder_ == null) {
        ensureUserWithPostIsMutable();
        userWithPost_.add(index, builderForValue.build());
        onChanged();
      } else {
        userWithPostBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .UserWithPost userWithPost = 1;</code>
     */
    public Builder addAllUserWithPost(
        java.lang.Iterable<? extends com.icemelon404.community.feed.proto.UserWithPost> values) {
      if (userWithPostBuilder_ == null) {
        ensureUserWithPostIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, userWithPost_);
        onChanged();
      } else {
        userWithPostBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .UserWithPost userWithPost = 1;</code>
     */
    public Builder clearUserWithPost() {
      if (userWithPostBuilder_ == null) {
        userWithPost_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        userWithPostBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .UserWithPost userWithPost = 1;</code>
     */
    public Builder removeUserWithPost(int index) {
      if (userWithPostBuilder_ == null) {
        ensureUserWithPostIsMutable();
        userWithPost_.remove(index);
        onChanged();
      } else {
        userWithPostBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .UserWithPost userWithPost = 1;</code>
     */
    public com.icemelon404.community.feed.proto.UserWithPost.Builder getUserWithPostBuilder(
        int index) {
      return getUserWithPostFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .UserWithPost userWithPost = 1;</code>
     */
    public com.icemelon404.community.feed.proto.UserWithPostOrBuilder getUserWithPostOrBuilder(
        int index) {
      if (userWithPostBuilder_ == null) {
        return userWithPost_.get(index);  } else {
        return userWithPostBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .UserWithPost userWithPost = 1;</code>
     */
    public java.util.List<? extends com.icemelon404.community.feed.proto.UserWithPostOrBuilder> 
         getUserWithPostOrBuilderList() {
      if (userWithPostBuilder_ != null) {
        return userWithPostBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(userWithPost_);
      }
    }
    /**
     * <code>repeated .UserWithPost userWithPost = 1;</code>
     */
    public com.icemelon404.community.feed.proto.UserWithPost.Builder addUserWithPostBuilder() {
      return getUserWithPostFieldBuilder().addBuilder(
          com.icemelon404.community.feed.proto.UserWithPost.getDefaultInstance());
    }
    /**
     * <code>repeated .UserWithPost userWithPost = 1;</code>
     */
    public com.icemelon404.community.feed.proto.UserWithPost.Builder addUserWithPostBuilder(
        int index) {
      return getUserWithPostFieldBuilder().addBuilder(
          index, com.icemelon404.community.feed.proto.UserWithPost.getDefaultInstance());
    }
    /**
     * <code>repeated .UserWithPost userWithPost = 1;</code>
     */
    public java.util.List<com.icemelon404.community.feed.proto.UserWithPost.Builder> 
         getUserWithPostBuilderList() {
      return getUserWithPostFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.icemelon404.community.feed.proto.UserWithPost, com.icemelon404.community.feed.proto.UserWithPost.Builder, com.icemelon404.community.feed.proto.UserWithPostOrBuilder> 
        getUserWithPostFieldBuilder() {
      if (userWithPostBuilder_ == null) {
        userWithPostBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.icemelon404.community.feed.proto.UserWithPost, com.icemelon404.community.feed.proto.UserWithPost.Builder, com.icemelon404.community.feed.proto.UserWithPostOrBuilder>(
                userWithPost_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        userWithPost_ = null;
      }
      return userWithPostBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:FeedPushRequest)
  }

  // @@protoc_insertion_point(class_scope:FeedPushRequest)
  private static final com.icemelon404.community.feed.proto.FeedPushRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.icemelon404.community.feed.proto.FeedPushRequest();
  }

  public static com.icemelon404.community.feed.proto.FeedPushRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FeedPushRequest>
      PARSER = new com.google.protobuf.AbstractParser<FeedPushRequest>() {
    @java.lang.Override
    public FeedPushRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FeedPushRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FeedPushRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FeedPushRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.icemelon404.community.feed.proto.FeedPushRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

