// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FeedServiceProto.proto

package com.icemelon404.community.feed.proto;

public interface UserWithPostOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserWithPost)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 feedOwnerId = 1;</code>
   * @return The feedOwnerId.
   */
  long getFeedOwnerId();

  /**
   * <code>int64 postId = 2;</code>
   * @return The postId.
   */
  long getPostId();
}
